Update Nodes.yaml

diff --git a/.github/workflows/Nodes.yaml b/.github/workflows/Nodes.yaml
--- a/.github/workflows/Nodes.yaml
+++ b/.github/workflows/Nodes.yaml
@@ -38,7 +38,7 @@ jobs:
          cat 1 2 > 3 && rm 1 2
          base64 3 > https -w 0 && rm 3
     - name: 提交更改
-      run: ./.github/update-repo.sh || echo -e "\033[33mWarning：git push Failed \033[0m"
+      run: ./.github/update-repo.sh || echo -e "\033[33;37mWarning：git push Failed\033[0m"
   long:
     needs: my-job
     runs-on: ubuntu-latest
